### ISSUE TITLE
一个新需求

### ISSUE THREAD

**Issue by linluz** [ArchiDog1998/PersistentDataEditor#2]
当参数（需设置多个数值）中的值不存在时，给其填写一个数值时，其他值直接自动输入默认值。
比如 我拖一个点参数 电池下来， 输入x的值为2并回车后，此电池会自动给未填写的yz填入0。这样既可以减少操作者的工作量 也不影响操作者后续继续修改yz。
代码部分：则可以再确认输入后，检查参数的值是否存在，若不存在 直接赋给默认值，再修改对应的部分即可
 另外 ：我看到你在占位符的说明文字里 不要复制，我觉得你已经通过注入让他可编辑了 直接也注入重写他的复制方法 让他报错 或者 内部无具体代码都行

**Comment by Ted-Jin-Lab** [comment]
有道理，输入一个值以后，别的值可以输入默认的，这个确实能减少输入的量。后面的代码部分和另外，我没看懂，不知道能否再解释一下？

**Comment by linluz** [comment]
代码部分只是我的一个实现思路而已。不重要 哈哈哈。
另外指的是：如果你不希望用户复制占位符电池的话，可以重写占位符电池的复制函数/事件，让其失效。类似于你的插件让它变得可以编辑一样

**Comment by linluz** [comment]
代码部分只是我的一个实现思路而已。不重要 哈哈哈。
另外指的是：如果你不希望用户复制占位符电池的话，可以重写占位符电池的复制函数/事件，让其失效。类似于你的插件让它变得可以编辑一样
