### ISSUE TITLE
一个新的建议

### ISSUE THREAD

**Issue by linluz** [ArchiDog1998/PersistentDataEditor#3]
点参数电池 在犀牛中拾取引用后，会导致 输入框的值都变成NaN。但从逻辑上来说它的行为应该更适合像 “输入端被连入参数”那样，直接让输入框消失。

**Comment by Ted-Jin-Lab** [comment]
有道理，应该设定，如果是引用了Rhino的物件，就不应该显示出来，下个版本更改。
