### ISSUE TITLE
一个新的bug

### ISSUE THREAD

**Issue by linluz** [ArchiDog1998/PersistentDataEditor#4]
![image](https://user-images.githubusercontent.com/15703508/189414381-03032c46-34ec-48d1-9be4-8de5dcb9e590.png)
如图输出端不应该显示修改文本框，我记得参数电池 带有一个枚举属性，来表示自身是输入、输出 、浮动。你可以借此来修复此bug。

**Comment by Ted-Jin-Lab** [comment]
对，呃，不过没看懂哪里有问题。

**Comment by linluz** [comment]
> 

没事 是我看错了
