### ISSUE TITLE
1.2.7 causes Python3 components in Grasshopper to fail loading.

### ISSUE THREAD

**Issue by timonielsen** [ArchiDog1998/PersistentDataEditor#6]
![image](https://github.com/ArchiDog1998/PersistentDataEditor/assets/5574797/d97e5fc2-8d98-4b65-bdcd-0f3222b8252b)

When using Python3 components and this is turned on it fails to initialize the component.

**Comment by Ted-Jin-Lab** [comment]
Thanks for your feedback! I reproduced this bug, let me fix it!

**Comment by Ted-Jin-Lab** [comment]
It was fixed in 1.2.8!
